#!/bin/bash

echo "=========================================="
echo "🎉 DUOTASK - DEPLOYMENT COMPLETE!"
echo "=========================================="
echo ""
echo "✅ WEB APP DEPLOYED"
echo "   🌐 URL: https://duotask-9rofgm9cs-sanjeevs-projects-e08bbbfb.vercel.app"
echo "   📱 Access from any device, any browser"
echo "   🔗 No installation required"
echo ""
echo "✅ DISCORD BOT RUNNING"
echo "   🤖 Bot Name: DuoTask#6160"
echo "   ✅ Status: Online and ready"
echo "   📝 Commands registered and working"
echo ""
echo "🔗 INVITE BOT TO YOUR DISCORD SERVER"
echo "   Visit this URL:"
echo "   https://discord.com/oauth2/authorize?client_id=1440406561393737892&permissions=2147485696&integration_type=0&scope=bot+applications.commands"
echo ""
echo "📋 AVAILABLE DISCORD COMMANDS"
echo "   /register email:you@email.com password:pass123 name:YourName"
echo "   /login email:you@email.com password:pass123"
echo "   /task title:\"Buy groceries\" urgent:true"
echo "   /list"
echo "   /pair"
echo "   /accept code:ABC123"
echo ""
echo "🧪 TESTING GUIDE"
echo ""
echo "Option 1: Web App Testing"
echo "   1. Open: https://duotask-9rofgm9cs-sanjeevs-projects-e08bbbfb.vercel.app"
echo "   2. Register an account"
echo "   3. Create tasks by tapping the +"
echo "   4. Test pairing with another device/browser"
echo ""
echo "Option 2: Discord Bot Testing"
echo "   1. Invite bot using URL above"
echo "   2. In any channel: /register"
echo "   3. Create tasks: /task title:\"Test task\""
echo "   4. View tasks: /list"
echo "   5. Generate pairing code: /pair"
echo ""
echo "🚀 MULTI-PLATFORM SYNC TEST"
echo "   1. Register on web app"
echo "   2. Login with same account on Discord: /login"
echo "   3. Create task on web → See it in Discord with /list"
echo "   4. Create task on Discord → See it sync to web!"
echo ""
echo "📊 BOT STATUS"
echo "   Check if bot is running:"
echo "   ps aux | grep 'node index.js' | grep -v grep"
echo ""
echo "   View bot logs:"
echo "   tail -f /Users/sanjeevjha/duo/duotask/discord-bot/bot.log"
echo ""
echo "   Restart bot if needed:"
echo "   cd /Users/sanjeevjha/duo/duotask/discord-bot"
echo "   pkill -f 'node index.js'"
echo "   nohup node index.js > bot.log 2>&1 &"
echo ""
echo "=========================================="
echo "✨ BOTH PLATFORMS ARE LIVE AND READY!"
echo "=========================================="
