#!/bin/bash

echo "================================================"
echo "🚀 EASY WEB APP DEPLOYMENT - NETLIFY DROP"
echo "================================================"
echo ""
echo "Vercel is having permission issues. Let's use Netlify instead!"
echo ""
echo "📦 Your web app is ready in: build/web/"
echo ""
echo "✅ OPTION 1: Netlify Drop (EASIEST - 30 seconds)"
echo "================================================"
echo ""
echo "1. Open this URL in your browser:"
echo "   👉 https://app.netlify.com/drop"
echo ""
echo "2. Drag and drop this folder into the browser:"
echo "   📁 /Users/sanjeevjha/duo/duotask/build/web"
echo ""
echo "3. Done! You'll get a live URL like:"
echo "   https://duotask-abc123.netlify.app"
echo ""
echo "================================================"
echo ""
echo "✅ OPTION 2: Test Locally (WORKS NOW)"
echo "================================================"
echo ""
echo "Your app is running at:"
echo "👉 http://localhost:8000"
echo ""
echo "Open in browser and test it!"
echo ""
echo "================================================"
echo ""
echo "💡 TIP: The local version (localhost:8000) works perfectly."
echo "    Use Netlify Drop for a public URL you can share!"
echo ""

# Open Netlify Drop page
read -p "Would you like to open Netlify Drop now? [y/N]: " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    open "https://app.netlify.com/drop"
    echo "✅ Opening Netlify Drop..."
    echo "   Just drag the build/web folder into the browser!"
fi
