#!/bin/bash

echo "🔍 DuoTask Database Connection Helper"
echo "====================================="

echo ""
echo "📋 To connect to your Supabase database via terminal, you need:"
echo ""
echo "1. Database Password (from Supabase Dashboard):"
echo "   - Go to: https://supabase.com/dashboard/project/xqhlnuvpogiolzkucupt/settings/database"
echo "   - Look for 'Database Password'"
echo "   - Copy the password"
echo ""
echo "2. Database URL:"
echo "   - Same page, look for 'Connection string' or 'Database URL'"
echo "   - It should look like: postgresql://postgres:[password]@db.xqhlnuvpogiolzkucupt.supabase.co:5432/postgres"
echo ""

echo "🚀 Once you have the password, run:"
echo ""
echo "supabase db remote psql -p [YOUR_PASSWORD]"
echo ""
echo "Or connect directly with psql:"
echo ""
echo "psql 'postgresql://postgres:[password]@db.xqhlnuvpogiolzkucupt.supabase.co:5432/postgres'"
echo ""

echo "📝 Alternative: Use the web interface"
echo "====================================="
echo "1. Go to: https://supabase.com/dashboard/project/xqhlnuvpogiolzkucupt/sql"
echo "2. Copy and paste the contents of 'quick_diagnostic.sql'"
echo "3. Click 'Run'"
echo "4. Share the results with me"
echo ""

echo "🔧 Quick Fix Option"
echo "=================="
echo "If you want to skip the diagnostic and go straight to fixing:"
echo "1. Go to: https://supabase.com/dashboard/project/xqhlnuvpogiolzkucupt/sql"
echo "2. Copy and paste the contents of 'update_database.sql'"
echo "3. Click 'Run'"
echo "4. Restart your Flutter app"
echo ""

echo "Your project details:"
echo "- Project ID: xqhlnuvpogiolzkucupt"
echo "- URL: https://xqhlnuvpogiolzkucupt.supabase.co"
echo "- Region: East US (North Virginia)"
