// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:931322985925:web:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '931322985925',
    projectId: 'duotask-app',
    authDomain: 'duotask-app.firebaseapp.com',
    storageBucket: 'duotask-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:931322985925:android:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '931322985925',
    projectId: 'duotask-app',
    storageBucket: 'duotask-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:931322985925:ios:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '931322985925',
    projectId: 'duotask-app',
    storageBucket: 'duotask-app.appspot.com',
    iosClientId: '931322985925-oor0nc6g69l447l2ng9fpmkd4fbeksjh.apps.googleusercontent.com',
    iosBundleId: 'com.duotask.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:931322985925:ios:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '931322985925',
    projectId: 'duotask-app',
    storageBucket: 'duotask-app.appspot.com',
    iosClientId: '931322985925-oor0nc6g69l447l2ng9fpmkd4fbeksjh.apps.googleusercontent.com',
    iosBundleId: 'com.duotask.app',
  );
} 