// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU_iNcp2KLrF0tg0u3CLQSDm0LVtHCeOw',
    appId: '1:687931195851:android:af7a29e27fd6b44069f64e',
    messagingSenderId: '687931195851',
    projectId: 'duotask-c0885',
    storageBucket: 'duotask-c0885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7OSaHC8MeQocZixKkTJPCweVf41zOgBM',
    appId: '1:687931195851:ios:ea039ee83a0d8b0669f64e',
    messagingSenderId: '687931195851',
    projectId: 'duotask-c0885',
    storageBucket: 'duotask-c0885.firebasestorage.app',
    iosBundleId: 'com.namaste.duotask.duotask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7OSaHC8MeQocZixKkTJPCweVf41zOgBM',
    appId: '1:687931195851:ios:ea039ee83a0d8b0669f64e',
    messagingSenderId: '687931195851',
    projectId: 'duotask-c0885',
    storageBucket: 'duotask-c0885.firebasestorage.app',
    iosBundleId: 'com.namaste.duotask.duotask',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7OSaHC8MeQocZixKkTJPCweVf41zOgBM',
    appId: '1:687931195851:web:af7a29e27fd6b44069f64e',
    messagingSenderId: '687931195851',
    projectId: 'duotask-c0885',
    storageBucket: 'duotask-c0885.firebasestorage.app',
    authDomain: 'duotask-c0885.firebaseapp.com',
  );
}
